#-----------------------------------------------#
#                   ZuusTweaks
#
#                    MikeBloc
#-----------------------------------------------#
# https://github.com/mikebloc/


#-----------------------------------------------#
# Toggles
#-----------------------------------------------#
DroppableEnderChest: true

InstaKillWither: true

UnbreakableAnvils: true

# Armor, Equipment, and Tools. Players and Mobs.
UnbreakableItems: true

# Minecarts are slightly faster.
FasterMinecart: true

# Saplings do not drop at all.
LimitedTrees: false

#-----------------------------------------------#
# Server Spawn Configs
#-----------------------------------------------#
# To bypass, perm is "zuusTweaks.bypass"

# These Worlds will have SpawnEffects at their center.
# Works for dimensions as well!
WorldNames:
  - hub_oasis
  - hub_proxy2

# This is how many blocks from X to -X and Z and -Z. Center of world.
ServerSpawnSize: 150

# Within the size above - Water/Lava won't flow near/at spawn.
BlockLiquidFlow: false

# Within the size above - Cannot break/place blocks, signs, etc.
# To bypass, perm is "zuusTweaks.bypass"
BlockManipulation: false

# Within the size above - Have increased foot speed. (FOV not affected)
SpeedBoost: false

# Within the size above - Block explosions from mobs and TNT
BlockExplosions: false

# Within the size above - Players cannot be harmed.
BlockPlayerDamage: false

# Within the size down - Hunger will not go down.
BlockPlayerHunger: false

# Within the size down - Mobs cannot be harmed.
BlockHurtingMobs: false

# Within the size down - Named Mobs cannot be harmed.
BlockHurtingNamedMobs: false

# Within the size down - Monster won't chase and endlessly attack.
BlockMonsterAgro: false